TRUNCATE catalog_returns;
TRUNCATE store;
TRUNCATE dbgen_version;
TRUNCATE item;
TRUNCATE web_page;
TRUNCATE promotion;
TRUNCATE inventory;
TRUNCATE web_sales;
TRUNCATE store_sales;
TRUNCATE catalog_sales;
TRUNCATE call_center;
TRUNCATE income_band;
TRUNCATE date_dim;
TRUNCATE reason;
TRUNCATE store_returns;
TRUNCATE web_returns;
TRUNCATE customer_demographics;
TRUNCATE warehouse;
TRUNCATE ship_mode;
TRUNCATE customer_address;
TRUNCATE time_dim;
TRUNCATE household_demographics;
TRUNCATE web_site;
TRUNCATE customer;
TRUNCATE catalog_page;

\copy catalog_returns FROM '../../dataset/third_party/tpcds-kit/tools/catalog_returns.dat' DELIMITER '|' NULL '';
\copy store FROM '../../dataset/third_party/tpcds-kit/tools/store.dat' DELIMITER '|' NULL '';
\copy dbgen_version FROM '../../dataset/third_party/tpcds-kit/tools/dbgen_version.dat' DELIMITER '|' NULL '';
\copy item FROM '../../dataset/third_party/tpcds-kit/tools/item.dat' DELIMITER '|' NULL '';
\copy web_page FROM '../../dataset/third_party/tpcds-kit/tools/web_page.dat' DELIMITER '|' NULL '';
\copy promotion FROM '../../dataset/third_party/tpcds-kit/tools/promotion.dat' DELIMITER '|' NULL '';
\copy inventory FROM '../../dataset/third_party/tpcds-kit/tools/inventory.dat' DELIMITER '|' NULL '';
\copy web_sales FROM '../../dataset/third_party/tpcds-kit/tools/web_sales.dat' DELIMITER '|' NULL '';
\copy store_sales FROM '../../dataset/third_party/tpcds-kit/tools/store_sales.dat' DELIMITER '|' NULL '';
\copy catalog_sales FROM '../../dataset/third_party/tpcds-kit/tools/catalog_sales.dat' DELIMITER '|' NULL '';
\copy call_center FROM '../../dataset/third_party/tpcds-kit/tools/call_center.dat' DELIMITER '|' NULL '';
\copy income_band FROM '../../dataset/third_party/tpcds-kit/tools/income_band.dat' DELIMITER '|' NULL '';
\copy date_dim FROM '../../dataset/third_party/tpcds-kit/tools/date_dim.dat' DELIMITER '|' NULL '';
\copy reason FROM '../../dataset/third_party/tpcds-kit/tools/reason.dat' DELIMITER '|' NULL '';
\copy store_returns FROM '../../dataset/third_party/tpcds-kit/tools/store_returns.dat' DELIMITER '|' NULL '';
\copy web_returns FROM '../../dataset/third_party/tpcds-kit/tools/web_returns.dat' DELIMITER '|' NULL '';
\copy customer_demographics FROM '../../dataset/third_party/tpcds-kit/tools/customer_demographics.dat' DELIMITER '|' NULL '';
\copy warehouse FROM '../../dataset/third_party/tpcds-kit/tools/warehouse.dat' DELIMITER '|' NULL '';
\copy ship_mode FROM '../../dataset/third_party/tpcds-kit/tools/ship_mode.dat' DELIMITER '|' NULL '';
\copy customer_address FROM '../../dataset/third_party/tpcds-kit/tools/customer_address.dat' DELIMITER '|' NULL '';
\copy time_dim FROM '../../dataset/third_party/tpcds-kit/tools/time_dim.dat' DELIMITER '|' NULL '';
\copy household_demographics FROM '../../dataset/third_party/tpcds-kit/tools/household_demographics.dat' DELIMITER '|' NULL '';
\copy web_site FROM '../../dataset/third_party/tpcds-kit/tools/web_site.dat' DELIMITER '|' NULL '';
\copy customer FROM '../../dataset/third_party/tpcds-kit/tools/customer.dat' DELIMITER '|' NULL '';
\copy catalog_page FROM '../../dataset/third_party/tpcds-kit/tools/catalog_page.dat' DELIMITER '|' NULL '';